apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: contour
  namespace: default
spec:
  serviceAccountName: contour-contour-sa
  packageRef:
    refName: contour.tanzu.vmware.com
    versionSelection:
      constraints: 1.18.2+vmware.1-tkg.1
  values:
  - secretRef:
      name: contour-contour-values
